### ISSUE TITLE
Adaption to Login form?

### ISSUE THREAD

**Issue by systemofapwne** [panpaul/keycloak-turnstile#2]
Can this plugin be adopted towards the login form too?

I was previously using https://github.com/raptor-group/keycloak-login-recaptcha as reCAPTCHA plugin on the login form. That repo explains on how to add it to the login form.
I would like to replace reCAPTCHA with turnstile on my login page. I think, modifications are minimal in order to support login with turnstile.

**Comment by panpaul** [comment]
Sorry, I've been quite busy recently and might not have time to implement this (at least for this month). :cry: However, you can try modifying it yourself. Turnstile offers a compatibility mode for reCaptcha, allowing for quick switching. You can check out the documentation [here](https://developers.cloudflare.com/turnstile/migration/migrating-from-recaptcha/)

**Comment by panpaul** [comment]
Should be solved by #3
